stages:
  - build

build_latex_document:
  stage: build
  image: ubuntu:latest
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y texlive-full make
  script:
    - make
    - mkdir -p public
    - echo "<html><body><ul>" > public/index.html
    - |
      for file in Compiled/*.pdf; do
        echo "<li><a href=\"$file\">$(basename "$file")</a></li>" >> public/index.html
      done
    - cp -r Compiled/ public/
    - echo "</ul></body></html>" >> public/index.html
  artifacts:
    paths:
      - public/
  only:
    - main
