name: Compile LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX environment
        uses: dante-ev/latex-action@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          # Add any additional latex packages you need here
          latexmk_shell_escape: true
          latexmk_use_lualatex: true

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: compiled-document
          path: main.pdf
