name: Compile LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile sheets
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            make

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-document
          path: main.pdf
